name: Build Linux AOT

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore
      run: dotnet restore
      
    - name: Publish Linux AOT
      run: |
        dotnet publish \
          -c Release \
          -r linux-x64 \
          --self-contained true \
          /p:PublishAot=true
          
    - name: Show publish directories
      run: |
        find . -type d | grep publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64
        path: |
          bin/Release/net10.0/linux-x64/publish/*